### ISSUE TITLE
Preveri uporabnika

### ISSUE THREAD

**Issue by MajaKomic** [saraconta/OPB-kozmeticni-salon#3]
Pozdravljeni,

pri funkciji '/stranke' (datoteka app.py, vrstica 287) sem naletela na težavo, da ko se oseba prijavi, funkcija ne prebere uporabnika. Poskusila sem s funkcijo preveriUporabnika (datoteka app.py, vrstica 61) tako kot je funkcijo uporabil prof Orbanić, in s funkcijo cookie_required_stranka (datoteka app.py, vrstica 75). V obeh primerih funkcije vrne, da je uporabnik None, torej da se je potrebno ponovno prijaviti.

Hvala za pomoč,
Maja

**Comment by majbc1999** [comment]
Živjo,

se opravičujem za pozen odgovor, sem bil na morju :D. Vidim, da ste že popravili?

**Comment by klaratravnik** [comment]
Živjo,
ja smo uspele razrešiti težavo. Hvala :)
